########## Windows

- hosts: localhost
  tasks:

  #  Criando usuario e definindo senha
  - name: Cria o usuário setic e coloca no grupo Administratores
    win_user:
      name: setic
      #password: "{{ setic_password }}"
      update_password: on_create
      state: present
      groups:
        - Administradores
    when: ansible_os_family == 'Windows'

  - name: Remove o usuário ctic2
    win_user:
      name: ctic2
      state: absent

  # Instalando e removendo programas via chocolatey e cria atalho
  - name: Instala programas via chocolatey
    win_chocolatey: name={{ item }} # state=latest timeout=9000
    with_items:
    - googlechrome
    - jre8
    - firefox
    - librecad
    when: ansible_os_family == 'Windows'

  - name: Instalar o microsoftsecurityessentials - Windows 7
    win_chocolatey:
      name: microsoftsecurityessentials
    when: (ansible_os_family == 'Windows' and ansible_os_name == 'Microsoft Windows 7 Professional')

  - name: Instalar o Unity 2018.2.10 - Windows
    win_chocolatey:
      name: unity
      version: '2018.2.10'
    when: ansible_os_family == 'Windows'

  - name: Cria o atalho do LibreCad 
    win_shortcut:
      src: C:\Program Files (x86)\LibreCAD\LibreCAD.exe
      dest: C:\Users\Public\Desktop\LibreCAD.lnk
      icon: C:\Program Files (x86)\LibreCAD\LibreCAD.exe,0
    when: ansible_os_family == 'Windows'

  # Criando pasta
  - name: Cria a pasta C:\instaladores\ 
    win_file:
      path: C:\instaladores\
      state: directory
    when: ansible_os_family == 'Windows'

  # Instalar programa .exe .msi com senha para Download
  - name: Baixar o instalador do Bricscad
    win_get_url:
      url: 'https://discovirtual.ifsc.edu.br/remote.php/webdav/SJE/CTIC/BricsCAD-V18.2.20-1-pt_BR(x64).msi'
      dest: 'C:\users\BricsCAD-V18.2.20-1-pt_BR(x64).msi'
      force: no
      url_username: "{{ url_username }}"
      url_password: "{{ url_password }}"
      timeout: 120
    when: ansible_os_family == 'Windows'

  - name: Baixar e instalar o BricsCAD
    win_package:
      path: 'C:\users\BricsCAD-V18.2.20-1-pt_BR(x64).msi'
      arguments: 'BRXLICENSESERVER="dko" SHOWRELEASENOTES=""'
      product_id: '{0A1EBB09-ADAB-4E6B-9185-54D12E8FBE56}'
      state: present
    when: ansible_os_family == 'Windows'

  # Agendamento de tarefas no Windows e alteração do plano de energia
  - name: Tarefa para desligar os computadores as 23h
    win_scheduled_task:
      name: desliga
      description: Desligar as 23h
      actions:
      - path: shutdown.exe
        arguments: -s -f -t 0
      triggers:
      - type: daily
        start_boundary: '23:00:00'
      username: SYSTEM
      state: present
      enabled: yes
    when: ansible_os_family == 'Windows'

  - name: Altera plano de energia para alto desempenho (não hiberna)
    win_power_plan:
      name: alto desempenho
    when: ansible_os_family == 'Windows'


  # Editando o Regedit e setando timezone
  - name: Configura servidor NTP para o Windows 1
    win_regedit:
      path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\DateTime\Servers
      name: 1
      data: gps.ntp.br
    when: ansible_os_family == 'Windows'

  - name: Setar timezone no Windows
    win_timezone:
      timezone: E. South America Standard Time
    when: ansible_os_family == 'Windows'


########## Linux

- hosts: localhost
  become: true
  vars_files:
    - token_agatha_reitoria.yaml
  tasks:

  # Criando usuario e definindo senha
  - name: Cria usuário aluno com a senha aluno e adicionar ao grupo sudo
    user:
      name: aluno
      groups: sudo
      password: $6$B5dpvoG43l67q0sx$r0LDKV2TgNItf/kYx/76l89ZN4LhP/ksYIxp.SSVGttHoSZXLSoB6Hkg2A6y7M7aFJ8zEuauf5kS/yA/P61kN1
      append: yes
    when: ansible_os_family == 'Debian'
  
  # Adicionando chave compartilhada
  - name: Adicionar entrada da chave pública no /root/.ssh/authorized_keys (Gabriel)
    authorized_key:
      user: root
      state: present
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCxZ6W+iZn1dlWBBxLI3ZHup8LRGk4YpnynlG8Fm4oLdM/2fWKupyl8SJDity0m13AVQBMgpR2k/BA1HLFnWjPpxsjsA03ORTVFG3zGN8Yqb0LRuPfpXmQTQtVtGkN7FD4JKyzFeY+G4J0K3mVjOO2F8pGLvrota6q0/8fNfMsHt0uDZpC9c34qM6Xq72ZChJhnq4JY0QT6fzu2BmVnjDz4eBDlrsbtzdgkNF+z1jLdd4xSYgqFhUIrhU8Bsf6vGQMR0CRFh8huKaDCb4/y2F0NmIX0Y5ycwNfOHwvUoIYJMgv0bWv8Ewfg1MsEQ2MxN67H/4/zmMjo9jM7c40R7nmFwhm4pMMCpH8R7DoLAm4g1cKt80GXaef+7OBuluVcV6qOzaIMhBhOxjZomBgw/fjnUSjWrwJEHXNsAE8/gQLaM6OyMVl0L53FL1f8CuhQC618yge9DhM2yDw7IBxxteyA6Mp1GNPSx0HFFqisEZD0q7ZxW3PQMaTqM3Gdf+ONTP1tGbEirPn3YB3erqaYwirRNERcOpJqh/h9ahi8A9HLmSgOB0JGwKPS39ZBDU4OplIWhHY4QT6orzbrO/IkNXv7DxKQjt9N/kytVpP7MNgB6Mrepi4FDA2OUNKYCZ31c29SFOAUWjjd6K5r4W3JTbJtxVjME4/ifd6oQQHFdNIl2w== gabriel.souza@sj-ctic-29736"
    when: ansible_os_family == 'Debian'

  - name: Adicionar entrada da chave pública no /home/aluno/.ssh/authorized_keys (Gabriel)
    authorized_key:
      user: aluno
      state: present
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCxZ6W+iZn1dlWBBxLI3ZHup8LRGk4YpnynlG8Fm4oLdM/2fWKupyl8SJDity0m13AVQBMgpR2k/BA1HLFnWjPpxsjsA03ORTVFG3zGN8Yqb0LRuPfpXmQTQtVtGkN7FD4JKyzFeY+G4J0K3mVjOO2F8pGLvrota6q0/8fNfMsHt0uDZpC9c34qM6Xq72ZChJhnq4JY0QT6fzu2BmVnjDz4eBDlrsbtzdgkNF+z1jLdd4xSYgqFhUIrhU8Bsf6vGQMR0CRFh8huKaDCb4/y2F0NmIX0Y5ycwNfOHwvUoIYJMgv0bWv8Ewfg1MsEQ2MxN67H/4/zmMjo9jM7c40R7nmFwhm4pMMCpH8R7DoLAm4g1cKt80GXaef+7OBuluVcV6qOzaIMhBhOxjZomBgw/fjnUSjWrwJEHXNsAE8/gQLaM6OyMVl0L53FL1f8CuhQC618yge9DhM2yDw7IBxxteyA6Mp1GNPSx0HFFqisEZD0q7ZxW3PQMaTqM3Gdf+ONTP1tGbEirPn3YB3erqaYwirRNERcOpJqh/h9ahi8A9HLmSgOB0JGwKPS39ZBDU4OplIWhHY4QT6orzbrO/IkNXv7DxKQjt9N/kytVpP7MNgB6Mrepi4FDA2OUNKYCZ31c29SFOAUWjjd6K5r4W3JTbJtxVjME4/ifd6oQQHFdNIl2w== gabriel.souza@sj-ctic-29736"
    when: ansible_os_family == 'Debian'

  # Instalando e removendo programas do repositório
  - name: Instalar pacotes do repositório comum
    apt: name={{ packages }} state=latest
    vars:
      packages:
      - kolourpaint4
      - icedtea-netx 
      - icedtea-8-plugin
      - openjdk-8-doc
      - openjdk-8-jdk
      - openjdk-8-jre

  - name: Remover programas  - Linux
    apt: name={{ packages }} state=absent
    vars:
      packages:
      - transmission
      - transmission-common
    when: ansible_os_family == 'Debian'

  # Instalando programas .deb
  - name: Install o Google Chrome
    apt:
      deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

  # Instalando programa do repositório não oficial, adicionando repositório e chave (Virtualbox)
  - name: Adicionar a chave do repositório do virtualbox 
    apt_key:
      url:  https://www.virtualbox.org/download/oracle_vbox_2016.asc
      state: present

  - name: Adicionar a chave do repositório do virtualbox 2
    apt_key:
      url:  https://www.virtualbox.org/download/oracle_vbox.asc
      state: present

  - name: Adicionar repositório do virtualbox
    apt_repository:
      repo: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian bionic contrib
      state: present
      update_cache: yes

  - name: Instalar o virtualbox
    apt: name={{ packages }} state=latest
    vars:
      packages:
      - virtualbox-6.0

  # Definindo versao do java e javac padroes
  - name: Definir versão java padrão - Linux
    alternatives:
      name: java
      path: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
    when: ansible_distribution == 'Debian'

  - name: Definir versão javac padrão - Linux
    alternatives:
      name: javac
      path: /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
    when: ansible_distribution == 'Debian'
